### ISSUE TITLE
New account creation, login, guest/demo login

### ISSUE THREAD

**Issue by polkadotazn** [polkadotazn/UNCHEEZD#2]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x] Demo User Added
 - [x] Styling
 - [x] Smooth, bug free navigation
   - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
 - [x] Adequate and appropriate seeds

**Comment by xnanodax** [comment]
I would replace the current bullets with the following bullets to add more detail:
```
 - [ ] Backend: DB, model, controller, views
 - [ ] Redux Loop: ajax, actions, reducer
 - [ ] Presentational Components
 - [ ] Demo User Added
 - [ ] Styling
 - [ ] Smooth, bug free navigation
   - [ ] Login errors clears when switching from login form to sign up form (and vice-versa)
 - [ ] Adequate and appropriate seeds
```

**Comment by xnanodax** [comment]
- [ ] Demo Login does not work. Error received: Invalid login credentials

**Comment by xnanodax** [comment]
- [ ] Accessing a random route like `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`

**Comment by xnanodax** [comment]
Awesome work! This issue is closed!
