### ISSUE TITLE
Cheese CRUD

### ISSUE THREAD

**Issue by polkadotazn** [polkadotazn/UNCHEEZD#3]
- [x] cheese index
- [x] cheese show page
- [x] create cheese
- [x] research cheeses
- [x] seed cheese data
- [x] update cheese
- [x] delete cheeses
- [x] cheese styling

**Comment by xnanodax** [comment]
- [ ] When adding a cheese, received an error: POST https://uncheezd.herokuapp.com/api/cheeses 422 (Unprocessable Entity)

**Comment by xnanodax** [comment]
- [ ] Still receiving same error when adding a cheese (status: 424)

**Comment by polkadotazn** [comment]
It should be good now! I was having trouble pushing to Heroku last night but I was able to today.

**Comment by xnanodax** [comment]
Great work :)! I would delete some console logs. Other than that, this issue is closed!
![screen shot 2018-02-09 at 1 33 18 pm](https://user-images.githubusercontent.com/20424731/36051098-d2ef6c5a-0d9d-11e8-9cc8-69ae7b6f995a.png)
