### ISSUE TITLE
Production Readme

### ISSUE THREAD

**Issue by polkadotazn** [polkadotazn/UNCHEEZD#7]
- [x] Overview
- [x] Technologies used
- [x] Features
- [x] Pictures and styling
- [x] Future directions

**Comment by xnanodax** [comment]
- [ ] Add screen clippings instead of screen shots!

**Comment by polkadotazn** [comment]
What is the difference between screen clippings vs screen shots?

**Comment by xnanodax** [comment]
Oh whoops never mind! You are fine. Closing this issue :)
